# This workflow is specifically for setting up a demo for drift detection
# in anchore enterprise.  Don't use this for other purposes.

name: Drift Detection Demo

on: 
  workflow_dispatch:
    inputs:
      mode:
        description: 'Manual Build'  
jobs:

  Build-Push:
    runs-on: ubuntu-latest
    env:
      ANCHORE_CLI_USER: ${{ secrets.ANCHORE_CLI_USER }}
      ANCHORE_CLI_PASS: ${{ secrets.ANCHORE_CLI_PASS }}
      ANCHORE_CLI_URL: ${{ secrets.ANCHORE_CLI_URL }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Login to ghcr.io
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${GITHUB_ACTOR} --password-stdin
    - name: Build Baseline Docker Image
      run: |
        docker build . --file .drift-demo/Dockerfile-nopy --tag ghcr.io/${GITHUB_REPOSITORY,,}:drift-demo
    - name: Push Baseline Docker Image
      run: |
        docker push ghcr.io/${GITHUB_REPOSITORY,,}:drift-demo
    - name: Install anchore-cli
      run: |
        sudo apt-get install python3-pip
        pip install anchorecli
        export PATH="$HOME/.local/bin/:$PATH"
    - name: Verify Anchore Ready and Reachable
      run: |
        anchore-cli system status 
    - name: Add Baseline Image to Enterprise Queue
      run: | 
        anchore-cli image add --noautosubscribe --dockerfile ./Dockerfile ghcr.io/${GITHUB_REPOSITORY,,}:drift-demo
    - name: Build Drifted Docker Image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/${GITHUB_REPOSITORY,,}:drift-demo
    - name: Push Drifted Docker Image
      run: |
        docker push ghcr.io/${GITHUB_REPOSITORY,,}:drift-demo
    - name: Wait for Baseline Image Analysis
      run: |
        anchore-cli image wait ghcr.io/${GITHUB_REPOSITORY,,}:drift-demo
        # I check this after the build/push of the drifted image just to save time, otherwise
        # we would just block while baseline scans even though we could be doing other stuff
    - name: Add Drifted Image to Enterprise Queue
      run: | 
        anchore-cli image add --noautosubscribe --dockerfile ./Dockerfile ghcr.io/${GITHUB_REPOSITORY,,}:drift-demo
    - name: Wait for Drifted Image Analysis
      run: |
        anchore-cli image wait ghcr.io/${GITHUB_REPOSITORY,,}:drift-demo
    - name: Activate Policy and Vulnerability Subscriptions
      run: |
        anchore-cli subscription activate policy_eval ghcr.io/${GITHUB_REPOSITORY,,}:drift-demo
        anchore-cli subscription activate vuln_update ghcr.io/${GITHUB_REPOSITORY,,}:drift-demo


